build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

init:
  - "ECHO %PYTHON%"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade setuptools"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install numpy"
  - "%PYTHON%\\python.exe -m pip  install ."
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

before_test:
- ps: >-
    $webclient = New-Object System.Net.WebClient
    
    $basedir = $pwd.Path + "\"
    
    $filepath = $basedir + "opengl32sw-32.7z"

    # Download and retry up to 3 times in case of network transient errors.
    
    # $url = "http://download.qt.io/development_releases/prebuilt/llvmpipe/windows/opengl32sw-32.7z"
    
    # $webclient.DownloadFile($url, $filepath)
    
    # 7z x opengl32sw-32.7z
    
    # dir
    
    
    # echo "Replacing Old OpenGL with new OpenGL"
    
    # regsvr32 /u opengl32.dll
    
    # regsvr32 /i opengl32sw.dll
    
    # echo "Register Success"
    
    SET APPVEYOR=1



test_script:
  - "%PYTHON%\\python.exe setup.py test"

artifacts:
  - path: dist/*.whl
    name: wheels

deploy:
  description: 'Release'
  provider: GitHub
  auth_token:
    secure: D0rvssFNbvMjYjXk+CAaNb2bklH7Y6/cLfU9x3614cY9EoKi4JgdvB5l9o4IfieQ
  artifact: /.*\.whl/
  draft: false
  prerelease: false
  on:
    branch: windows-wheels
    APPVEYOR_REPO_TAG: true
